### ISSUE TITLE
Milestone 1 Checklist

### ISSUE THREAD

**Issue by PhilsChan** [UBC-MDS/Web-Cloud-Group17#1]
- [x] Team-work Contract @gn385x

Github Repo @PhilsChan 
- [x] Create Repo + Project Structure
- [x] Update README

Milestone 1 notebook
- [x] Download data from API @PhilsChan 
- [x] Combine data CSVs + Compare @PhilsChan 
- [x] Simple EDA + Compare @AraiYuno 
- [x] EDA in R @jamesktkim @gn385x
